### ISSUE TITLE
Nome do projeto fixo no código

### ISSUE THREAD

**Issue by gil27** [kleytonmr/ecs-task-management#8]
https://github.com/kleytonmr/ecs-task-management/blob/e3a15541c23663011283bfc7f751d3e72f390f1b/ecs_tasks.sh#L132

**Comment by kleytonmr** [comment]
Você me ajudou a resolver um bug sem saber, @gil27 hahah. 

O nome do contêiner estava chumbado. Eu deixei assim na época pra testar porque não estava conseguindo pegar o nome do container de forma iterativa. 

O que isso causou? Só era possível acessar as tarefas quando o serviço era do mesmo contexto. Se fosse uma tarefa de outro contexto, o nome do contêiner seria diferente e estava quebrando. Eu tinha até desistido. "Poxa, por quê só funciona pra esse contexto mas quando eu vou para o outro, acontece isso?" 👏🏼 

Obrigado pela ajuda mano. 

O erro: 
![image](https://github.com/kleytonmr/ecs-task-management/assets/31089959/343bc9f2-f8d0-475c-9a35-6f624f2e7096)

PR de correção: https://github.com/kleytonmr/ecs-task-management/pull/11
